# Generated by Django 5.2.15 on 2026-06-20 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.URLField(max_length=2048)),
                ('is_private', models.BooleanField(default=False)),
                ('redirect_identifier', models.CharField(editable=False, max_length=8, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redirect Rule',
                'verbose_name_plural': 'Redirect Rules',
                'ordering': ['-created'],
            },
        ),
    ]
